# Generated by Django 2.1.5 on 2020-08-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
